### ISSUE TITLE
Question: using this snippet in a CRON job

### ISSUE THREAD

**Issue by osabate** [BobRay/QuickEmail#2]
Since the user has to be authenticated to run this snippet I was wondering how I could run this snippet as a CRON job.
I'm thinking about dupplicating it, removing the authentication piece and placing it under a private directory.

`/* to be removed */  if (! $modx->user->hasSessionContext('mgr')) return 'Unauthorized';`

What you reckon?

**Comment by BobRay** [comment]
I can't think of any reason why it wouldn't work.

**Comment by osabate** [comment]
Thanks for your quick response @BobRay. Is this how you would approach this problem? Any better way?

**Comment by BobRay** [comment]
I would just take the email section of QuickEmail and create a new snippet. QuickEmail is designed to diagnose email problems, so much of it would be wasted if you just want to send a scheduled email.

**Comment by osabate** [comment]
The idea is to send a daily email to make sure email works. I guess if something is wrong it won't send anything anyways.. good point! Closing it. Thanks!
